### ISSUE TITLE
Post-mode Lock-up

### ISSUE THREAD

**Issue by lag-linaro** [Boruch-Baum/post-mode#8]
I'm experiencing a Fontify related lock-up issue when in `post-mode`.

After setting `debug-on-event` to `sigusr2` and sending a `USR2` signal to the running process, it chucks out:

```
Debugger entered--entering a function:                                                                                       
* #f(compiled-function () #<bytecode 0x157408928bc1>)()                                                                      
  font-lock-default-fontify-region(16 17 nil)                                                                                
  font-lock-fontify-region(16 17)                                                                                            
  #f(compiled-function (fun) #<bytecode 0x157408928b8d>)(font-lock-fontify-region)                                           
  run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x157408928b8d>) font-lock-fontify-region)                          
  jit-lock--run-functions(16 17)                                                                                             
  jit-lock-fontify-now(16 516)                                                                                               
  jit-lock-function(16)                                                                                                      
  redisplay_internal\ \(C\ function\)() 
```

**Comment by lag-linaro** [comment]
Video of the issue: https://asciinema.org/a/5B7Ds1WIdeOXvYLo07DatLtQO

**Comment by lag-linaro** [comment]
Appears to occur whenever there is a blank line in the file.

Either in an existing file opened with `post-mode` or issuing successive `RET`s.

**Comment by Boruch-Baum** [comment]
On 2021-06-15 04:07, Lee Jones wrote:
>    Appears to occur whenever there is a blank line in the file.
>
>    Either in an existing file opened with post-mode or issuing successive
>    RETs.

Hi. I can't reproduce this. Also, the asciicinema wasn't very useful
because I couldn't get the form factor of the screencast to scale to fit
my display, so I was only able to view either the top/bottom of the
screen cast, but not see the entire screen. That doesn't mean the
screencast was worthless, but it didn't add anything you couldn't have
easily told me.

Some of the first things that I did learn immediately from the
screencast was that you launched something called 'cemacs' and that you
did so without command-line argument '-Q'. I have no idea what cemacs
is, a cursory web search didn't help me figure that out, and I don't see
it available in my OS distribution's repositories for me to try out.
Presuming that what you're running is a faithful emacs clone the next
step would be to try running it in its version of 'emacs -Q', ie.
without any configuration or init file being loaded. In doing so, be
careful that some OS distributions have 'system-wide' custom
configurations on top of the 'vanilla' program, so whatever 'cemacs' is,
the idea would be to run it with whatever command-line arguments to not
load either set.

As for the emacs compatibility version number, that would be good to
know, but if cemacs is a faithful emacs clone might not be necessary in
this particular case because the 'post-mode' package has been so
sleepy-stable for so many years over so many versions of emacs.

Finally, emacs has a command M-x toggle-debug-on-error which would save
you needing to send the process a SIGUSR if that convenience is useful
to you.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by lag-linaro** [comment]
Thanks for the detailed reply.

`cemacs` is just an alias for `emacs -nw` (no-window).

The version I'm running is `GNU Emacs 27.1`. It's the default install in `Ubuntu 21.04`.

I didn't get the bottom of it, but the issue *was* related to `post-mode` unfortunately. 

I managed to fix it by installing my Distro's version via the package-manager instead of using this one directly.

**Comment by Boruch-Baum** [comment]
On 2021-06-15 06:41, Lee Jones wrote:
>    I managed to fix it by installing my Distro's version via the
>    package-manager instead of using this one directly.

You mean the Ubuntu 21.04 repository version of post-mode?

If you're happy, great, you can close the issue if you want. I can't
reproduce the error in debian with emacs 27.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by lag-linaro** [comment]
Yes, the repo version of `post-mode` seems to work without issue. 

Looks like it's the older one (from 2014) with the outdated back-tick format removed.

I'll close this for now, but just be aware that something strange is going on, probably with some missing deps.

Best of luck.
